Update auto-pr.yml
Signed-off-by: Thabani Chibanda <tchibanda24@gmail.com>

diff --git a/templates/workflows/auto-pr.yml b/templates/workflows/auto-pr.yml
--- a/templates/workflows/auto-pr.yml
+++ b/templates/workflows/auto-pr.yml
@@ -1,13 +1,27 @@
-name: Pull Request on Branch Push
+# This workflow will automatically create a new pull request when a new branch is pushed and validated
+# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
+
+name: Validate Branch & Open PR
 
 on: [ push ]
 
 env:
   GH_TOKEN: ${{ github.token }}
+  BRANCH_NAME: ${GITHUB_REF#refs/heads/}
       
 jobs:
-  auto-pull-request:
+  validate-branch:
+  name: Validate Branch
+    steps:
+      - name: Validate branch name
+        if: !startsWith( github.ref_name, 'feature') && !startsWith( github.ref_name, 'fix') && !startsWith( github.ref_name, 'task') && !startsWith( github.ref_name, 'refactor') && !startsWith( github.ref_name, 'revert')
+        run: |
+          echo "Invalid branch name, must start with: feature, fix, task, refactor, or revert."
+          exit 1 
+              
+  create-pull-request:
     name: Create New PR From Branch
+    needs: validate-branch # This causes the step to abort if validation failed
     runs-on: ubuntu-latest
     
     steps:
